name: smart_css

services:
  node:
    build:
      context: ..
      dockerfile: docker/Node.Dockerfile
    environment:
      HISTFILE: /root/log/.history
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
    volumes:
      - ../:/app
      - ../docker/tmp/.history:/root/log/.history
    working_dir: /app
